# Generated by Django 4.0.4 on 2022-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0008_vehiclepassport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepassport',
            options={'verbose_name_plural': 'Паспорта машин'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepassport',
            name='engine_volume',
            field=models.SmallIntegerField(verbose_name='Объем двигателя, куб.см'),
        ),
        migrations.AlterField(
            model_name='vehiclepassport',
            name='vin',
            field=models.CharField(max_length=30, verbose_name='Идентификационный номер (VIN)'),
        ),
    ]
