# Generated by Django 4.0.4 on 2022-05-12 02:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0009_alter_auto_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
                ('object_volvo', django.db.models.manager.Manager()),
            ],
        ),
    ]
