# Generated by Django 4.0.4 on 2022-05-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0010_alter_auto_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
            ],
        ),
    ]
