# Generated by Django 4.0.4 on 2022-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0014_alter_auto_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210),
        ),
    ]
